// lib/scheduleData.js
const scheduleData = [
    {
      time: '10:00 AM',
      monday: 'Muay Thai',
      tuesday: 'MMA',
      wednesday: 'Kids MMA',
      thursday: 'Open Mat',
      friday: 'No Gi Grappling',
      saturday: 'MMA',
      sunday: 'Tiny Classes (ages 3-5)',
    },
    {
      time: '11:00 AM',
      monday: 'MMA',
      tuesday: 'Muay Thai',
      wednesday: 'MMA',
      thursday: 'Muay Thai',
      friday: 'Open Mat',
      saturday: 'Muay Thai',
      sunday: 'Tiny Classes (ages 3-5)',
    },
    {
      time: '12:00 PM',
      monday: 'Kids MMA',
      tuesday: 'Kids MMA',
      wednesday: 'Muay Thai',
      thursday: 'Kids MMA',
      friday: 'Boxing',
      saturday: 'Junior Sparring',
      sunday: 'Tiny Classes (ages 3-5)',
    },
    {
      time: '1:30 PM',
      monday: 'Open Mat',
      tuesday: 'Open Mat',
      wednesday: 'Open Mat',
      thursday: 'No Gi Grappling',
      friday: 'MMA',
      saturday: 'Private Lessons',
      sunday: 'Tiny Classes (ages 3-5)',
    },
    {
      time: '2:30 PM',
      monday: 'No Gi Grappling',
      tuesday: 'No Gi Grappling',
      wednesday: 'Boxing',
      thursday: 'Boxing',
      friday: 'Muay Thai',
      saturday: 'Private Lessons',
      sunday: 'Tiny Classes (ages 3-5)',
    },
    {
      time: '3:30 PM',
      monday: 'MMA',
      tuesday: 'MMA',
      wednesday: 'BJJ',
      thursday: 'MMA',
      friday: 'Kids MMA',
      saturday: 'Private Lessons',
      sunday: 'Tiny Classes (ages 3-5)',
    },
    {
      time: '4:30 PM',
      monday: 'Junior Sparring',
      tuesday: 'Junior Sparring',
      wednesday: 'Women’s BJJ',
      thursday: 'Muay Thai',
      friday: 'Women’s BJJ',
      saturday: 'Private Lessons',
      sunday: 'Tiny Classes (ages 3-5)',
    },
    {
      time: '5:30 PM',
      monday: 'Fitness Training',
      tuesday: 'Fitness Training',
      wednesday: 'Junior Sparring',
      thursday: 'Kickboxing',
      friday: 'Kickboxing',
      saturday: 'Private Lessons',
      sunday: 'Tiny Classes (ages 3-5)',
    },
    {
      time: '6:30 PM',
      monday: 'Muay Thai',
      tuesday: 'Fitness Training',
      wednesday: 'Fitness Training',
      thursday: 'Junior Sparring',
      friday: 'Junior Sparring',
      saturday: 'Private Lessons',
      sunday: 'Tiny Classes (ages 3-5)',
    },
  ];
  
  export default scheduleData;
  