// lib/scheduleData.js

const scheduleData = [
  {
    time: '10:00am',
    monday: 'Adult Muaythai (invite only)',
    tuesday: 'Adult Muaythai (invite only)',
    wednesday: 'Adult Muaythai (invite only)',
    thursday: 'Adult Muaythai (invite only)',
    friday: 'Adult Muaythai (invite only)',
    saturday: '',
    sunday: '',
  },
  {
    time: '10:30am',
    monday: '',
    tuesday: '',
    wednesday: '',
    thursday: '',
    friday: '',
    saturday: 'Adult Muaythai',
    sunday: '',
  },
  {
    time: '3:00pm',
    monday: 'Adult Muaythai (invite only)',
    tuesday: 'Adult Muaythai (invite only)',
    wednesday: 'Adult Muaythai (invite only)',
    thursday: '',
    friday: '',
    saturday: '',
    sunday: '',
  },
  {
    time: '5:30pm',
    monday: 'Junior Muaythai',
    tuesday: 'Junior Muaythai',
    wednesday: 'Junior Muaythai',
    thursday: 'Junior Muaythai',
    friday: 'Junior Muaythai',
    saturday: '',
    sunday: '',
  },
  {
    time: '6:30pm',
    monday: 'Adult Muaythai',
    tuesday: 'Adult Muaythai',
    wednesday: 'Adult Muaythai',
    thursday: 'Adult Muaythai',
    friday: 'Adult Muaythai',
    saturday: '',
    sunday: '',
  },
  {
    time: '7:30pm',
    monday: 'Adult MMA Class',
    tuesday: '',
    wednesday: 'Adult MMA Class',
    thursday: '',
    friday: '',
    saturday: '',
    sunday: '',
  },
];

export default scheduleData;
